### ISSUE TITLE
getTransaction has a new parameter - includeTotals

### ISSUE THREAD

**Issue by omniwolf** [davesag/ir-api#775]
Please see here:

https://www.independentreserve.com/au/features/api#GetTransactions

> **includeTotals** - Defaults to `true` for backward compatibility. When set to `false`, response time is improved and the `TotalItems` and `TotalPages` properties are returned as `-1`. 

It's easy enough to alter ir-api getTransactions.js to allow this to work, just add it to the parameters payload:

```javascript
  return async ({
    accountGuid,
    fromTimestampUtc,
    toTimestampUtc,
    txTypes,
    pageIndex = defaultParams.pageIndex,
    pageSize = defaultParams.pageSize,
    includeTotals
  }) => {
    const payload = {
      accountGuid,
      fromTimestampUtc,
      toTimestampUtc,
      txTypes,
      pageIndex,
      pageSize,
      includeTotals
    }
``` 

The allowable values are strings, "true" or "false".
Eg;

```javascript
                const singleCurrencyTransactions = await getTransactions({
                    accountGuid: currency_dict[accounts[acc].currencyCode],
                    txTypes: ['Withdrawal'],
                    fromTimestampUtc: fromTimestampUtc.toISOString(),
                    toTimestampUtc: toTimestampUtc.toISOString(),
                    pageSize: 100,
                    includeTotals: "false"
                });
``` 

However, I'm not smart enough to put this into the validation code.  I'm guessing you can make use of the `isOneOf.js` validation, but I'm not sure how.
I can create a PR for the above stuff if you want to then add the validation to it, or just leave it with you.

**Comment by davesag** [comment]
hey - sorry for the delay - I have merged your PR but there's a few out of date deps I should also upgrade before I issue a new release.  I'll close this now as your PR

**Comment by omniwolf** [comment]
Hi, sorry I'm not sure I understand your message.
Just to be clear - there is no PR for this issue as I don't know how to properly do the validation for the two allowable values (`"true"` and `"false"`).  The issue shouldn't be closed - it still exists.
I can create a PR to add the `includeTotals` feature if you want, but there will be no validation.

**Comment by davesag** [comment]
Ah sorry I got carried away. Please reopen and I’ll take another look. DSent from my iPhoneOn 3 Jun 2024, at 10:34 PM, Nick ***@***.***> wrote:﻿
Hi, sorry I'm not sure I understand your message.
Just to be clear - there is no PR for this issue as I don't know how to properly do the validation for the two allowable values ("true" and "false").  The issue shouldn't be closed - it still exists.
I can create a PR to add the includeTotals feature if you want, but there will be no validation.

**Comment by davesag** [comment]
Okay now fixed.
